Cnmf yx streamline
cellarium-ai/cellarium-ml pull request #269
Opened 2024-11-13 19:39 UTC by ImXman

cnmf pipeline workable in jupyter notebook. More tests needed for terminal execution.

2024-11-13 20:58 UTC, sjfleming requested changes
Nice work!  I left several comments.  Please either make changes or reply to each of them so that we can figure out where to make changes.

Also I set things up so that the github actions tests run automatically on this pull request.  Make sure that these tests are all passing.  If tests fail, find and fix the problems.  (I would first try these command line commands: `make format` and `make typecheck`.)  Currently the `nmf` branch is passing tests (https://github.com/cellarium-ai/cellarium-ml/pull/196).

2024-11-13 20:58 UTC, sjfleming commented on cellarium/ml/cli.py
> +def nmf_consensus(args: ArgsType = None) -> None:
Do we still want this command line command?

2024-11-13 20:58 UTC, sjfleming commented on cellarium/ml/core/module.py
> +    def on_train_end(self) -> None:
I do not think this is necessary.  See the comment on the `on_end()` function in nmf.py

2024-11-13 20:58 UTC, sjfleming commented on cellarium/ml/core/module.py
> +    def on_predict_end(self) -> None:
I am not sure if this is necessary.  See the comment on the `on_prediction_end()` function in nmf.py

2024-11-13 20:58 UTC, sjfleming commented on cellarium/ml/models/nmf.py
> +    def nmf_forward(self, x_ng: torch.Tensor, var_names_g: np.ndarray) -> dict[str, torch.Tensor | None]:
I do not think we should split things into `nmf_forward()` and `consensus_forward()`.  Can't we have just one `forward()` function?  If `r == 1`, then we are doing regular NMF, and if `r > 1` then we are doing consensus NMF.  But the code could be the exact same.  Just the `r` dimension of tensors will have size 1 if we are doing regular NMF.  Right?

2024-11-13 20:58 UTC, sjfleming commented on cellarium/ml/models/nmf.py
> +    def consensus_forward(
I recommend changing the name of this to `forward()`

2024-11-13 20:58 UTC, sjfleming commented on cellarium/ml/models/nmf.py
> +            self.forward = self.consensus_forward
Based on comments below, I recommend getting rid of this

2024-11-13 20:58 UTC, sjfleming commented on examples/cli_workflow/nmf_heart_config.yaml
> +# lightning.pytorch==2.2.1
Let's include only one config file, and let's have it be the config file that is used by the notebook tutorial for cNMF.

2024-11-13 20:58 UTC, sjfleming commented on notebooks/nmf_human_heart_consensu_tutorial.ipynb
> +{
Let's include headers and explanations in this notebook.  Make it look clear and understandable.

2024-11-20 23:19 UTC, sjfleming commented on cellarium/ml/models/nmf.py
> +                                     local_neighborhood_size=density_threshold)
I think this should say 
```python
local_neighborhood_size= local_neighborhood_size
```

2024-11-20 23:26 UTC, sjfleming commented on cellarium/ml/models/nmf.py
> +    adata = anndata.concat(adatas, axis=0, merge="same")
These lines of code to not appear to be used in what follows

2024-11-20 23:27 UTC, sjfleming commented on cellarium/ml/models/nmf.py
> +    pipeline[-1].the_best_k=20
This seems to be overwriting the input `the_best_k`, which is being ignored

2024-11-21 02:18 UTC, ImXman commented on cellarium/ml/models/nmf.py
> +                                     local_neighborhood_size=density_threshold)
Corrected

2024-12-11 20:09 UTC, sjfleming commented on cellarium/ml/cli.py
> +def nmf_consensus(args: ArgsType = None) -> None:
done

2024-12-11 21:43 UTC, merged