Geneformer
cellarium-ai/cellarium-ml pull request #64
Opened 2023-08-03 18:10 UTC by ordabayevy

See https://huggingface.co/ctheodoris/Geneformer

2023-09-07 16:57 UTC, mbabadi requested changes

2023-09-07 16:57 UTC, mbabadi commented on cellarium/ml/module/base_module.py
> +    def predict(self, *args: Any, **kwargs: Any) -> torch.Tensor | ModelOutput:
This is too broad of a mixin to be practically meaningful.  I suggest generalizing the original signature to the degree that might be needed, e.g. perhaps taking `Dict[str, torch.Tensor]` and input and `Dict[str, torch.Tensor]` as output, and wrapping huggingface models that produce `ModelOutput` to conform to _our_ predict mixin.

2023-09-07 16:57 UTC, mbabadi commented on cellarium/ml/module/geneformer.py
> +        output = self.model(
See my earlier comment about the signature of `predict`. Do we _need_ to have the output as `ModelOutput`, or can be cherrypick whatever we need from it and return something more mundane, like `Dict[str, torch.Tensor]`?

2023-09-11 17:44 UTC, ordabayevy commented on cellarium/ml/data/dadc_dataset.py
> +        data["var_names"] = self.dadc.var_names.values.copy()
Changed these to copies.

2023-09-11 17:44 UTC, ordabayevy commented on cellarium/ml/data/util.py
> +        assert all(keys == data.keys() for data in batch[1:]), "All dictionaries in the batch must have the same keys."
Added the check for dict keys.

2023-09-11 17:44 UTC, ordabayevy commented on cellarium/ml/module/base_module.py
> +    __call__: Callable[..., torch.Tensor | None]
This adds return type to the module call. In the `training_step` we expect it to be `Tensor` or `None`. Otherwise it returns `Any`.

2023-09-11 17:44 UTC, ordabayevy commented on cellarium/ml/module/base_module.py
> +    def predict(self, x_ng: torch.Tensor, **kwargs: Any) -> torch.Tensor | dict[str, torch.Tensor | None]:
Additional arguments are passed in as kwargs.

2023-09-11 17:44 UTC, ordabayevy commented on cellarium/ml/module/geneformer.py
> +        return (x,), {"feature_list": feature_list}
`features_list` is returned as part of dict.

2023-09-11 17:44 UTC, ordabayevy commented on cellarium/ml/module/geneformer.py
> +        feature_list: Sequence = kwargs.pop("feature_list")
`feature_list` is obtained from kwargs.

2023-09-11 17:44 UTC, ordabayevy commented on cellarium/ml/module/geneformer.py
> +        output_attentions: bool = kwargs.pop("output_attentions", True)
`output_hidden_states` and `output_attentions` can be passed through kwargs

2023-09-18 16:29 UTC, merged