Add perturbation functionality to geneformer's `.predict()` method
cellarium-ai/cellarium-ml pull request #98
Opened 2023-10-23 17:37 UTC by sjfleming

Adds the optional kwargs
```
feature_deletion
feature_activation
feature_map
```
to `Geneformer.predict()`

The idea of "deletion" and "activation" are described in the Geneformer paper. Deletion is achieved by zeroing expression before tokenization. Activation is achieved by setting feature expression to a high value so that it ends up at the top of the rank-ordered list.

"Map" is a general kind of idea to implement other kinds of _in silico_ experiments. It takes the data after tokenization, and maps token values to other values. This could be used to implement the replacement of a specific token or set of tokens with a pad (0) or mask (1) token, or to switch the role of two tokens, etc.

2023-10-23 17:37 UTC, sjfleming commented
Closes #98

2023-10-23 17:44 UTC, sjfleming commented
So far there are no tests covering the new functionality

2024-02-02 06:22 UTC, sjfleming commented
Added a test to cover the new functionality

2024-02-02 06:44 UTC, sjfleming commented
@ordabayevy I think I might need some help with the `mypy` error here.  It's coming from my added geneformer test.  It doesn't seem to like the way I'm trying to pass **kwargs as an input?  Do you know what's wrong?  The pytest test itself passes.

2024-02-02 06:55 UTC, sjfleming commented
Okay nevermind, I just did some extra copy and paste and now mypy seems happy.  I wonder how you're supposed to give **kwargs as an input in a way mypy will be happy with.

2024-02-06 20:15 UTC, ordabayevy requested changes
Looks great! Left some comments

2024-02-06 20:15 UTC, ordabayevy commented on cellarium/ml/models/geneformer.py
> +                assert feature_logic_g.sum() == 1, f"feature_activation element {g} is not in self.var_names_g"
nit: raise `ValueError`

2024-02-06 20:15 UTC, ordabayevy commented on cellarium/ml/models/geneformer.py
> +                assert feature_logic_g.sum() == 1, f"feature_map key {g} not in self.var_names_g"
nit: raise `ValueError`

2024-02-06 20:15 UTC, ordabayevy commented on cellarium/ml/models/geneformer.py
> +                initial_token = self.feature_ids[feature_logic_g]
I wonder if there would be any benefits of having a `gene_name -> gene_id` dictionary so we don't have to do this

2024-02-06 20:15 UTC, ordabayevy commented on tests/test_geneformer.py
> +    torch.testing.assert_close(input_ids, expected_input_ids)
I didn't know that `torch.testing`  existed!

2024-02-06 20:21 UTC, ordabayevy commented
Notebook comment: you can directly index `CellariumPipeline`:

```py
var_names_g = pipeline.get_submodule("2").var_names_g
# instead
var_names_g = pipeline[2].var_names_g
# or better
var_names_g = pipeline.model.var_names_g
```

2024-02-12 17:52 UTC, sjfleming commented on cellarium/ml/models/geneformer.py
> +            deletion_logic_g = np.logical_or.reduce([(self.var_names_g == g) for g in feature_deletion])
Great call, I did not realize that!

2024-02-13 18:22 UTC, ordabayevy approved these changes

2024-02-13 18:22 UTC, merged